#!/bin/bash

cd examples
python simple_models.py
python ref_column_models.py
python ref_model_models.py
python relationship_models.py
python relationship_models_traditional.py
python all_of_models.py
cd -
