
openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate OpenAlchemy MVP.
  version: "0.1"

paths:
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"
  /division:
    get:
      summary: Used to retrieve all divisions.
      responses:
        200:
          description: Return all divisions from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Division"

components:
  schemas:
    IdNameBase:
      description: Base schema with an id and name column.
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the object.
          example: 0
          x-primary-key: true
        name:
          type: string
          description: The name of the object.
          example: Object 1.
      required:
        - id
        - name
    Division:
      allOf:
        - "$ref": "#/components/schemas/IdNameBase"
        - description: A part of a company.
          x-tablename: division
    Employee:
      allOf:
        - "$ref": "#/components/schemas/IdNameBase"
        - description: Person that works for a company.
          x-tablename: employee
