"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member

from open_alchemy import models


class Division(models.Division):
    """Division SQLAlchemy model."""

    id: int
    name: str


class Employee(models.Employee):
    """Employee SQLAlchemy model."""

    id: int
    name: str
