"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member

import typing

from open_alchemy import models


class RefEmployee(models.RefEmployee):
    """RefEmployee SQLAlchemy model."""

    id: int
    name: str
    division: str
    salary: typing.Optional[float]
