"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member

import typing

from open_alchemy import models


class Project(models.Project):
    """Project SQLAlchemy model."""

    id: typing.Optional[int]
    name: typing.Optional[str]


class Employee(models.Employee):
    """Employee SQLAlchemy model."""

    id: typing.Optional[int]
    name: typing.Optional[str]
    projects: typing.Sequence["Project"]
