"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member

import typing

from open_alchemy import models


class PayInfo(models.PayInfo):
    """PayInfo SQLAlchemy model."""

    id: typing.Optional[int]
    account_number: typing.Optional[str]


class Employee(models.Employee):
    """Employee SQLAlchemy model."""

    id: int
    name: str
    pay_info: "PayInfo"
