"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member

import typing

from open_alchemy import models


class Division(models.Division):
    """Division SQLAlchemy model."""

    id: typing.Optional[int]
    name: typing.Optional[str]


class Employee(models.Employee):
    """Employee SQLAlchemy model."""

    id: int
    name: str
    division: "Division"
