"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""
# pylint: disable=no-member

import typing

from open_alchemy import models


class Employee(models.Employee):
    """Employee SQLAlchemy model."""

    id: int
    name: str
    address: typing.Optional[str]
    division: str
    salary: typing.Optional[float]
