"""Tests for models."""
# pylint: disable=protected-access

import pytest

from open_alchemy import models_file

DOCSTRING = '"""Autogenerated SQLAlchemy models based on OpenAlchemy models."""'


@pytest.mark.parametrize(
    "models, expected_source",
    [
        (
            ["model 1"],
            f"""{DOCSTRING}
# pylint: disable=no-member,useless-super-delegation

import typing

from open_alchemy import models
model 1
""",
        ),
        (
            ["model 1", "model 2"],
            f"""{DOCSTRING}
# pylint: disable=no-member,useless-super-delegation

import typing

from open_alchemy import models
model 1
model 2
""",
        ),
        (
            ["model 1 datetime."],
            f"""{DOCSTRING}
# pylint: disable=no-member,useless-super-delegation

import datetime
import typing

from open_alchemy import models
model 1 datetime.
""",
        ),
        (
            ["model 1 datetime.", "model 2 datetime."],
            f"""{DOCSTRING}
# pylint: disable=no-member,useless-super-delegation

import datetime
import typing

from open_alchemy import models
model 1 datetime.
model 2 datetime.
""",
        ),
    ],
    ids=[
        "single model",
        "multiple models",
        "contains datetime",
        "contains duplicate imports",
    ],
)
@pytest.mark.models_file
def test_generate(models, expected_source):
    """
    GIVEN single model
    WHEN generate is called
    THEN the source for the models file is returned.
    """
    source = models_file._models.generate(models=models)

    assert source == expected_source
